name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
          # python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
          # There's a bug in Python 3.6.0 that prevents pytest from working properly.
          # https://github.com/nedbat/coveragepy/issues/703
          # python-version: [3.10.0a2, 3.9, 3.8, 3.7, 3.6.1, 3.5, 3.4, 3.3]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Package Wheel
        run: |
          echo v0.0.0 > VERSION
          pip install wheel
          python setup.py bdist_wheel

      - name: Run Linter
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-pylint
          pip install -e .
          pytest --pylint -m pylint ./UKFastAPI

      - name: Run Tests
        env:
          UKF_API_KEY: ${{ secrets.UKF_API_KEY }}
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov vcrpy
          mv setup_ci.cfg setup.cfg
          pytest -vs